'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Partial Public Class Entry
    #Region "Primitive Properties"

    Public Overridable Property ID As Integer

    Public Overridable Property Name As String

    Public Overridable Property Age As Short

    #End Region
    #Region "Complex Properties"

    Public Overridable Property Address As AddressType
        Get
            Return _address
        End Get
        Set(ByVal value As AddressType)
            _address = value
        End Set
    End Property
    Private _address As New AddressType

    #End Region
    #Region "Navigation Properties"
    Public Overridable Property Categories As ICollection(Of Category)
        Get
            If _categories Is Nothing Then
                Dim newCollection As New FixupCollection(Of Category)
                AddHandler newCollection.CollectionChanged, AddressOf FixupCategories
                _categories = newCollection
            End If
            Return _categories
        End Get
        Set(ByVal value As ICollection(Of Category))
            If _categories IsNot value Then
                Dim previousValue As FixupCollection(Of Category) = TryCast(_categories, FixupCollection(Of Category))
                If previousValue IsNot Nothing Then
                    RemoveHandler previousValue.CollectionChanged, AddressOf FixupCategories
                End If
                _categories = value
                Dim newValue As FixupCollection(Of Category) = TryCast(value, FixupCollection(Of Category))
                If newValue IsNot Nothing Then
                    AddHandler newValue.CollectionChanged, AddressOf FixupCategories
                End If
            End If
        End Set
    End Property
    Private _categories As ICollection(Of Category)

    #End Region
    #Region "Association Fixup"
    Private Sub FixupCategories(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If e.NewItems IsNot Nothing Then
            For Each item As Category In e.NewItems
                If Not item.Entries.Contains(Me) Then
                    item.Entries.Add(Me)
                End If
            Next
        End If
        If e.OldItems IsNot Nothing Then
            For Each item As Category In e.OldItems
                If item.Entries.Contains(Me) Then
                    item.Entries.Remove(Me)
                End If
            Next
        End If
    End Sub

    #End Region
End Class
