'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.EntityClient

Partial Public Class AddressBookContainer
    Inherits ObjectContext
    Public Const SettingsConnectionString As String = "name=AddressBookContainer"
    Public Const ContainerName As String = "AddressBookContainer"

#Region "Constructors"

    Public Sub New()
        MyBase.New(SettingsConnectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

#End Region
#Region "ObjectSet Properties"

    Public ReadOnly Property Categories() As ObjectSet(Of Category)
        Get
            If _categories Is Nothing Then
                _categories = CreateObjectSet(Of Category)("Categories")
            End If
            Return _categories
        End Get
    End Property
    Private _categories As ObjectSet(Of Category)

    Public ReadOnly Property Entries() As ObjectSet(Of Entry)
        Get
            If _entries Is Nothing Then
                _entries = CreateObjectSet(Of Entry)("Entries")
            End If
            Return _entries
        End Get
    End Property
    Private _entries As ObjectSet(Of Entry)

#End Region
End Class
