//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ConsoleApplication1
{
    public partial class Category
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string CategoryName
        {
            get;
            set;
        }
    
        public virtual string Detail
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Entry> Entries
        {
            get
            {
                if (_entries == null)
                {
                    var newCollection = new FixupCollection<Entry>();
                    newCollection.CollectionChanged += FixupEntries;
                    _entries = newCollection;
                }
                return _entries;
            }
            set
            {
                if (!ReferenceEquals(_entries, value))
                {
                    var previousValue = _entries as FixupCollection<Entry>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupEntries;
                    }
                    _entries = value;
                    var newValue = value as FixupCollection<Entry>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupEntries;
                    }
                }
            }
        }
        private ICollection<Entry> _entries;

        #endregion
        #region Association Fixup
    
        private void FixupEntries(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Entry item in e.NewItems)
                {
                    if (!item.Categories.Contains(this))
                    {
                        item.Categories.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Entry item in e.OldItems)
                {
                    if (item.Categories.Contains(this))
                    {
                        item.Categories.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
