//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMStudy2
{
    using System;
    
    public partial class AddressType
    {
        public string TelNo { get; set; }
        public string MailAddress { get; set; }
    }
}
