//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMStudy2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Entries = new HashSet<Entry>();
        }
    
        public int ID { get; set; }
        public string CategoryName { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
    }
}
