//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMStudy1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public Entry()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string MailAddress { get; set; }
        public string TelNo { get; set; }
        public short Age { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
